FROM node:18.17.1

WORKDIR /usr/src/app
COPY package*.json ./

CMD npm install --prefer-offline && \
    npx wait-port metadata:80 && \
    npx wait-port history:80 && \
    npx wait-port advertise:80 && \
    npm run start:dev
