#
# To deploy:
#
# kubectl apply -f scripts/production-kub/advertise.yaml
#
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: advertise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advertise
  template:
    metadata:
      labels:
        app: advertise
    spec:
      containers:
        - name: advertise
          image: $CONTAINER_REGISTRY/advertise:1
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: advertise
spec:
  selector:
    app: advertise
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
